version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: valuenow-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-valuenow_root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-valuenow}
      MYSQL_USER: ${MYSQL_USER:-valuenow}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-valuenow_db}
    ports:
      - '3307:3306'
    volumes:
      - ./var/volume/mysql:/var/lib/myqsl

  webserver:
    container_name: valuenow-webserver-separate
    image: 'nginx:alpine'
    working_dir: /application
    volumes:
      - '.:/application'
      - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '22005:80'

  php-fpm:
    container_name: valuenow-php-fpm
    build: phpdocker/php-fpm
    working_dir: /application
    volumes:
      - '.:/application'
      - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
    environment:
      PHP_IDE_CONFIG: "serverName=valuenow_symfony"

